/*
SQLyog Community v10.3 
MySQL - 8.0.17 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `countries` (
	`id` bigint (20),
	`country_sotname_en` varchar (300),
	`name` char (150),
	`country_name_zh` char (150),
	`phonecode` char (150),
	`status` int (11),
	`created_at` timestamp ,
	`updated_at` timestamp 
); 
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('1','AF','Afghanistan','Afghanistan','93','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('2','AL','Albania','Albania','355','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('3','DZ','Algeria','Algeria','213','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('4','AS','American Samoa','American Samoa','1684','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('5','AD','Andorra','Andorra','376','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('6','AO','Angola','Angola','244','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('7','AI','Anguilla','Anguilla','1264','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('8','AQ','Antarctica','Antarctica','0','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('9','AG','Antigua And Barbuda','Antigua And Barbuda','1268','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('10','AR','Argentina','Argentina','54','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('11','AM','Armenia','Armenia','374','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('12','AW','Aruba','Aruba','297','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('13','AU','Australia','Australia','61','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('14','AT','Austria','Austria','43','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('15','AZ','Azerbaijan','Azerbaijan','994','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('16','BS','Bahamas The','Bahamas The','1242','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('17','BH','Bahrain','Bahrain','973','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('18','BD','Bangladesh','Bangladesh','880','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('19','BB','Barbados','Barbados','1246','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('20','BY','Belarus','Belarus','375','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('21','BE','Belgium','Belgium','32','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('22','BZ','Belize','Belize','501','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('23','BJ','Benin','Benin','229','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('24','BM','Bermuda','Bermuda','1441','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('25','BT','Bhutan','Bhutan','975','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('26','BO','Bolivia','Bolivia','591','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('27','BA','Bosnia and Herzegovina','Bosnia and Herzegovina','387','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('28','BW','Botswana','Botswana','267','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('29','BV','Bouvet Island','Bouvet Island','0','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('30','BR','Brazil','Brazil','55','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('31','IO','British Indian Ocean Territory','British Indian Ocean Territory','246','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('32','BN','Brunei','Brunei','673','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('33','BG','Bulgaria','Bulgaria','359','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('34','BF','Burkina Faso','Burkina Faso','226','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('35','BI','Burundi','Burundi','257','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('36','KH','Cambodia','Cambodia','855','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('37','CM','Cameroon','Cameroon','237','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('38','CA','Canada','Canada','1','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('39','CV','Cape Verde','Cape Verde','238','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('40','KY','Cayman Islands','Cayman Islands','1345','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('41','CF','Central African Republic','Central African Republic','236','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('42','TD','Chad','Chad','235','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('43','CL','Chile','Chile','56','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('44','CN','China','China','86','0',NULL,'2020-09-25 10:45:38');
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('45','CX','Christmas Island','Christmas Island','61','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('46','CC','Cocos (Keeling) Islands','Cocos (Keeling) Islands','672','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('47','CO','Colombia','Colombia','57','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('48','KM','Comoros','Comoros','269','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('49','CG','Republic Of The Congo','Republic Of The Congo','242','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('50','CD','Democratic Republic Of The Congo','Democratic Republic Of The Congo','242','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('51','CK','Cook Islands','Cook Islands','682','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('52','CR','Costa Rica','Costa Rica','506','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('53','CI','Cote D\'Ivoire (Ivory Coast)','Cote D\'Ivoire (Ivory Coast)','225','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('54','HR','Croatia (Hrvatska)','Croatia (Hrvatska)','385','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('55','CU','Cuba','Cuba','53','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('56','CY','Cyprus','Cyprus','357','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('57','CZ','Czech Republic','Czech Republic','420','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('58','DK','Denmark','Denmark','45','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('59','DJ','Djibouti','Djibouti','253','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('60','DM','Dominica','Dominica','1767','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('61','DO','Dominican Republic','Dominican Republic','1809','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('62','TP','East Timor','East Timor','670','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('63','EC','Ecuador','Ecuador','593','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('64','EG','Egypt','Egypt','20','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('65','SV','El Salvador','El Salvador','503','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('66','GQ','Equatorial Guinea','Equatorial Guinea','240','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('67','ER','Eritrea','Eritrea','291','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('68','EE','Estonia','Estonia','372','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('69','ET','Ethiopia','Ethiopia','251','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('70','XA','External Territories of Australia','External Territories of Australia','61','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('71','FK','Falkland Islands','Falkland Islands','500','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('72','FO','Faroe Islands','Faroe Islands','298','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('73','FJ','Fiji Islands','Fiji Islands','679','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('74','FI','Finland','Finland','358','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('75','FR','France','France','33','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('76','GF','French Guiana','French Guiana','594','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('77','PF','French Polynesia','French Polynesia','689','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('78','TF','French Southern Territories','French Southern Territories','0','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('79','GA','Gabon','Gabon','241','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('80','GM','Gambia The','Gambia The','220','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('81','GE','Georgia','Georgia','995','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('82','DE','Germany','Germany','49','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('83','GH','Ghana','Ghana','233','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('84','GI','Gibraltar','Gibraltar','350','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('85','GR','Greece','Greece','30','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('86','GL','Greenland','Greenland','299','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('87','GD','Grenada','Grenada','1473','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('88','GP','Guadeloupe','Guadeloupe','590','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('89','GU','Guam','Guam','1671','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('90','GT','Guatemala','Guatemala','502','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('91','XU','Guernsey and Alderney','Guernsey and Alderney','44','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('92','GN','Guinea','Guinea','224','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('93','GW','Guinea-Bissau','Guinea-Bissau','245','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('94','GY','Guyana','Guyana','592','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('95','HT','Haiti','Haiti','509','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('96','HM','Heard and McDonald Islands','Heard and McDonald Islands','0','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('97','HN','Honduras','Honduras','504','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('98','HK','Hong Kong S.A.R.','Hong Kong S.A.R.','852','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('99','HU','Hungary','Hungary','36','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('100','IS','Iceland','Iceland','354','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('101','IN','India','India','91','1',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('102','ID','Indonesia','Indonesia','62','0',NULL,'2020-09-25 10:46:02');
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('103','IR','Iran','Iran','98','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('104','IQ','Iraq','Iraq','964','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('105','IE','Ireland','Ireland','353','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('106','IL','Israel','Israel','972','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('107','IT','Italy','Italy','39','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('108','JM','Jamaica','Jamaica','1876','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('109','JP','Japan','Japan','81','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('110','XJ','Jersey','Jersey','44','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('111','JO','Jordan','Jordan','962','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('112','KZ','Kazakhstan','Kazakhstan','7','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('113','KE','Kenya','Kenya','254','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('114','KI','Kiribati','Kiribati','686','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('115','KP','Korea North','Korea North','850','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('116','KR','Korea South','Korea South','82','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('117','KW','Kuwait','Kuwait','965','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('118','KG','Kyrgyzstan','Kyrgyzstan','996','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('119','LA','Laos','Laos','856','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('120','LV','Latvia','Latvia','371','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('121','LB','Lebanon','Lebanon','961','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('122','LS','Lesotho','Lesotho','266','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('123','LR','Liberia','Liberia','231','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('124','LY','Libya','Libya','218','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('125','LI','Liechtenstein','Liechtenstein','423','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('126','LT','Lithuania','Lithuania','370','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('127','LU','Luxembourg','Luxembourg','352','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('128','MO','Macau S.A.R.','Macau S.A.R.','853','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('129','MK','Macedonia','Macedonia','389','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('130','MG','Madagascar','Madagascar','261','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('131','MW','Malawi','Malawi','265','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('132','MY','Malaysia','Malaysia','60','1',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('133','MV','Maldives','Maldives','960','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('134','ML','Mali','Mali','223','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('135','MT','Malta','Malta','356','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('136','XM','Man (Isle of)','Man (Isle of)','44','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('137','MH','Marshall Islands','Marshall Islands','692','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('138','MQ','Martinique','Martinique','596','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('139','MR','Mauritania','Mauritania','222','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('140','MU','Mauritius','Mauritius','230','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('141','YT','Mayotte','Mayotte','269','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('142','MX','Mexico','Mexico','52','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('143','FM','Micronesia','Micronesia','691','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('144','MD','Moldova','Moldova','373','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('145','MC','Monaco','Monaco','377','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('146','MN','Mongolia','Mongolia','976','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('147','MS','Montserrat','Montserrat','1664','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('148','MA','Morocco','Morocco','212','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('149','MZ','Mozambique','Mozambique','258','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('150','MM','Myanmar','Myanmar','95','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('151','NA','Namibia','Namibia','264','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('152','NR','Nauru','Nauru','674','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('153','NP','Nepal','Nepal','977','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('154','AN','Netherlands Antilles','Netherlands Antilles','599','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('155','NL','Netherlands The','Netherlands The','31','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('156','NC','New Caledonia','New Caledonia','687','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('157','NZ','New Zealand','New Zealand','64','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('158','NI','Nicaragua','Nicaragua','505','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('159','NE','Niger','Niger','227','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('160','NG','Nigeria','Nigeria','234','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('161','NU','Niue','Niue','683','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('162','NF','Norfolk Island','Norfolk Island','672','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('163','MP','Northern Mariana Islands','Northern Mariana Islands','1670','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('164','NO','Norway','Norway','47','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('165','OM','Oman','Oman','968','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('166','PK','Pakistan','Pakistan','92','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('167','PW','Palau','Palau','680','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('168','PS','Palestinian Territory Occupied','Palestinian Territory Occupied','970','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('169','PA','Panama','Panama','507','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('170','PG','Papua new Guinea','Papua new Guinea','675','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('171','PY','Paraguay','Paraguay','595','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('172','PE','Peru','Peru','51','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('173','PH','Philippines','Philippines','63','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('174','PN','Pitcairn Island','Pitcairn Island','0','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('175','PL','Poland','Poland','48','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('176','PT','Portugal','Portugal','351','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('177','PR','Puerto Rico','Puerto Rico','1787','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('178','QA','Qatar','Qatar','974','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('179','RE','Reunion','Reunion','262','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('180','RO','Romania','Romania','40','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('181','RU','Russia','Russia','70','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('182','RW','Rwanda','Rwanda','250','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('183','SH','Saint Helena','Saint Helena','290','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('184','KN','Saint Kitts And Nevis','Saint Kitts And Nevis','1869','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('185','LC','Saint Lucia','Saint Lucia','1758','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('186','PM','Saint Pierre and Miquelon','Saint Pierre and Miquelon','508','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('187','VC','Saint Vincent And The Grenadines','Saint Vincent And The Grenadines','1784','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('188','WS','Samoa','Samoa','684','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('189','SM','San Marino','San Marino','378','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('190','ST','Sao Tome and Principe','Sao Tome and Principe','239','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('191','SA','Saudi Arabia','Saudi Arabia','966','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('192','SN','Senegal','Senegal','221','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('193','RS','Serbia','Serbia','381','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('194','SC','Seychelles','Seychelles','248','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('195','SL','Sierra Leone','Sierra Leone','232','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('196','SG','Singapore','Singapore','65','1',NULL,'2020-09-25 10:44:37');
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('197','SK','Slovakia','Slovakia','421','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('198','SI','Slovenia','Slovenia','386','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('199','XG','Smaller Territories of the UK','Smaller Territories of the UK','44','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('200','SB','Solomon Islands','Solomon Islands','677','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('201','SO','Somalia','Somalia','252','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('202','ZA','South Africa','South Africa','27','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('203','GS','South Georgia','South Georgia','0','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('204','SS','South Sudan','South Sudan','211','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('205','ES','Spain','Spain','34','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('206','LK','Sri Lanka','Sri Lanka','94','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('207','SD','Sudan','Sudan','249','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('208','SR','Suriname','Suriname','597','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('209','SJ','Svalbard And Jan Mayen Islands','Svalbard And Jan Mayen Islands','47','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('210','SZ','Swaziland','Swaziland','268','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('211','SE','Sweden','Sweden','46','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('212','CH','Switzerland','Switzerland','41','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('213','SY','Syria','Syria','963','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('214','TW','Taiwan','Taiwan','886','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('215','TJ','Tajikistan','Tajikistan','992','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('216','TZ','Tanzania','Tanzania','255','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('217','TH','Thailand','Thailand','66','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('218','TG','Togo','Togo','228','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('219','TK','Tokelau','Tokelau','690','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('220','TO','Tonga','Tonga','676','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('221','TT','Trinidad And Tobago','Trinidad And Tobago','1868','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('222','TN','Tunisia','Tunisia','216','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('223','TR','Turkey','Turkey','90','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('224','TM','Turkmenistan','Turkmenistan','7370','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('225','TC','Turks And Caicos Islands','Turks And Caicos Islands','1649','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('226','TV','Tuvalu','Tuvalu','688','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('227','UG','Uganda','Uganda','256','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('228','UA','Ukraine','Ukraine','380','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('229','AE','United Arab Emirates','United Arab Emirates','971','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('230','GB','United Kingdom','United Kingdom','44','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('231','US','United States','United States','1','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('232','UM','United States Minor Outlying Islands','United States Minor Outlying Islands','1','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('233','UY','Uruguay','Uruguay','598','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('234','UZ','Uzbekistan','Uzbekistan','998','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('235','VU','Vanuatu','Vanuatu','678','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('236','VA','Vatican City State (Holy See)','Vatican City State (Holy See)','39','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('237','VE','Venezuela','Venezuela','58','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('238','VN','Vietnam','Vietnam','84','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('239','VG','Virgin Islands (British)','Virgin Islands (British)','1284','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('240','VI','Virgin Islands (US)','Virgin Islands (US)','1340','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('241','WF','Wallis And Futuna Islands','Wallis And Futuna Islands','681','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('242','EH','Western Sahara','Western Sahara','212','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('243','YE','Yemen','Yemen','967','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('244','YU','Yugoslavia','Yugoslavia','38','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('245','ZM','Zambia','Zambia','260','0',NULL,NULL);
insert into `countries` (`id`, `country_sotname_en`, `name`, `country_name_zh`, `phonecode`, `status`, `created_at`, `updated_at`) values('246','ZW','Zimbabwe','Zimbabwe','263','0',NULL,NULL);
